{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4a2ccdc-a834-481d-865d-ff9f32faa017",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, render_template, request, redirect, url_for\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing import image\n",
    "import numpy as np\n",
    "import os\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Load trained model\n",
    "model = tf.keras.models.load_model(\"model/pneumonia_model.h5\")\n",
    "\n",
    "def predict_pneumonia(img_path):\n",
    "    img = image.load_img(img_path, target_size=(150, 150))\n",
    "    x = image.img_to_array(img)\n",
    "    x = np.expand_dims(x, axis=0) / 255.0\n",
    "    pred = model.predict(x)\n",
    "    return \"Pneumonia\" if pred[0][0] > 0.5 else \"Normal\"\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    return render_template('index.html')\n",
    "\n",
    "@app.route('/predict', methods=['POST'])\n",
    "def upload_and_predict():\n",
    "    file = request.files['file']\n",
    "    if file:\n",
    "        filepath = os.path.join(\"static\", file.filename)\n",
    "        file.save(filepath)\n",
    "        prediction = predict_pneumonia(filepath)\n",
    "        return render_template('result.html', prediction=prediction, image_path=filepath)\n",
    "    return redirect(url_for('index'))\n",
    "\n",
    "@app.route('/doctor')\n",
    "def doctor():\n",
    "    doctors = [\n",
    "        {\"name\": \"Dr. Ramesh Kumar\", \"specialty\": \"Pulmonologist\", \"hospital\": \"Apollo Hospital\", \"contact\": \"9876543210\"},\n",
    "        {\"name\": \"Dr. Anjali Mehta\", \"specialty\": \"Respiratory Specialist\", \"hospital\": \"Fortis Hospital\", \"contact\": \"9876509876\"},\n",
    "        {\"name\": \"Dr. S. Sharma\", \"specialty\": \"Chest Specialist\", \"hospital\": \"AIIMS Delhi\", \"contact\": \"011-26588500\"}\n",
    "    ]\n",
    "    return render_template(\"doctor.html\", doctors=doctors)\n",
    "\n",
    "@app.route('/diet')\n",
    "def diet():\n",
    "    foods = [\n",
    "        \"Warm fluids (soup, herbal tea)\",\n",
    "        \"Fruits rich in Vitamin C (oranges, kiwi)\",\n",
    "        \"Vegetables (broccoli, spinach)\",\n",
    "        \"Protein-rich foods (eggs, pulses)\",\n",
    "        \"Avoid cold drinks and oily foods\"\n",
    "    ]\n",
    "    return render_template(\"diet.html\", foods=foods)\n",
    "\n",
    "@app.route('/progress')\n",
    "def progress():\n",
    "    progress_data = [\n",
    "        {\"day\": 1, \"status\": \"High fever, coughing\"},\n",
    "        {\"day\": 3, \"status\": \"Slight improvement\"},\n",
    "        {\"day\": 5, \"status\": \"Normal temperature\"},\n",
    "        {\"day\": 7, \"status\": \"Recovery phase\"},\n",
    "        {\"day\": 10, \"status\": \"Healthy!\"}\n",
    "    ]\n",
    "    return render_template(\"progress.html\", progress=progress_data)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
